### ISSUE TITLE
error. with new appdeamon 

### ISSUE THREAD

**Issue by botany112** [Petro31/ad_toggle_light#2]
are you still maintaining this add-on?

**Comment by Petro31** [comment]
There's not much to maintain unless AD changed their api

**Comment by botany112** [comment]
is it okay to show you my error? maybe you can see whats wrong?

**Comment by Petro31** [comment]
Yes, please post the error.

**Comment by botany112** [comment]
2023-08-30 22:00:05.637261 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2023-08-30 22:00:05.643758 INFO AppDaemon: App 'Koof_toggle' changed
2023-08-30 22:00:05.653054 INFO AppDaemon: Found 8 active apps
2023-08-30 22:00:05.653874 INFO AppDaemon: Found 0 inactive apps
2023-08-30 22:00:05.654499 INFO AppDaemon: Found 0 global libraries
2023-08-30 22:00:05.664826 INFO AppDaemon: Terminating Koof_toggle
2023-08-30 22:00:05.667759 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/ad_toggle_light/toggle_light.py
2023-08-30 22:00:05.668330 INFO AppDaemon: Loading App Module: toggle_light
2023-08-30 22:00:05.676331 WARNING Error: ------------------------------------------------------------
2023-08-30 22:00:05.677078 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad_toggle_light/toggle_light.py:
2023-08-30 22:00:05.677968 WARNING Error: ------------------------------------------------------------
2023-08-30 22:00:05.683383 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 763, in read_app
    importlib.reload(self.modules[module_name])
                     ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'toggle_light'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 768, in read_app
    self.read_app(file)
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad_toggle_light/toggle_light.py", line 2, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'
2023-08-30 22:00:05.684176 WARNING Error: ------------------------------------------------------------
2023-08-30 22:00:05.684712 WARNING AppDaemon: Removing associated apps:
2023-08-30 22:00:05.685314 WARNING AppDaemon: Koof_toggle
2023-08-30 22:00:05.886800 WARNING AppDaemon: Unexpected error refreshing default state - retrying in 10 minute

**Comment by botany112** [comment]
2023-08-30 22:05:59.537033 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad_toggle_light/toggle_light.py:
2023-08-30 22:05:59.537430 WARNING Error: ------------------------------------------------------------
2023-08-30 22:05:59.546080 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad_toggle_light/toggle_light.py", line 2, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

**Comment by Petro31** [comment]
@botany112 you need to load voluptuous as a dependency.  See the error.

**Comment by botany112** [comment]
what is that? module voluptuous?

**Comment by Petro31** [comment]
It's a python library that's required for this app.  You have to add it to your system.

**Comment by botany112** [comment]
ill look in to it. how to add that to my homeassitant.
its strange its stopped working. is something what they changed in hassio?
